services:
  db:
    image: postgres:17
    container_name: db_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_PASSWORD}", "-U", "${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
     - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_healthy
    ports:
     - "8009:8009"
    command: bash -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8009"



volumes:
  db_data:
    driver: local